# Generated by Django 6.0.5 on 2026-07-03 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('layerOrder', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
                ('svg_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('slug_name', models.CharField(max_length=10, null=True, unique=True)),
                ('color', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug_name', models.CharField(blank=True, max_length=200, null=True)),
                ('diagram_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('svg_id', models.CharField(max_length=100)),
                ('is_accessible', models.BooleanField(default=False)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformpathapp.layer')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformpathapp.station')),
            ],
        ),
        migrations.AddField(
            model_name='layer',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformpathapp.station'),
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_forward', models.CharField(max_length=300)),
                ('instruction_backward', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='platformpathapp.node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='platformpathapp.node')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformpathapp.station')),
            ],
        ),
        migrations.CreateModel(
            name='StationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_station', to='platformpathapp.line')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_line', to='platformpathapp.station')),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='lines',
            field=models.ManyToManyField(blank=True, through='platformpathapp.StationLine', to='platformpathapp.line'),
        ),
        migrations.AddConstraint(
            model_name='stationline',
            constraint=models.UniqueConstraint(fields=('station', 'line'), name='unique_station_line'),
        ),
        migrations.AddConstraint(
            model_name='stationline',
            constraint=models.UniqueConstraint(fields=('line', 'order'), name='unique_line_order'),
        ),
    ]
