# Generated by Django 5.2.14 on 2026-06-03 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('diagram_path', models.CharField(max_length=100)),
                ('lines', models.ManyToManyField(blank=True, to='platformpathapp.line')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('svg_id', models.CharField(max_length=100)),
                ('layer', models.CharField(max_length=100)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformpathapp.station')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_forward', models.CharField(max_length=300)),
                ('instruction_backward', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='platformpathapp.node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='platformpathapp.node')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformpathapp.station')),
            ],
        ),
    ]
