# Generated by Django 5.2.14 on 2026-06-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformpathapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_accessible',
            field=models.BooleanField(default=False),
        ),
    ]
