# Generated by Django 6.0.5 on 2026-07-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformpathapp', '0008_layer_and_node_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('NONE', 'None'), ('EXT_STRS', 'Exit Stairs'), ('STRS', 'Stairs'), ('PLTFRM', 'Platform'), ('MEZZ', 'Mezzanine'), ('MEZZ_B', 'Mezzanine B'), ('RMP', 'Ramp'), ('ELVTR', 'Elevator'), ('ESCLTR', 'Escalator')], default='NONE', max_length=20),
        ),
    ]
