# Generated by Django 6.0.5 on 2026-07-23 01:42

import platformpathapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformpathapp', '0009_alter_node_node_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='node_type',
        ),
        migrations.AddField(
            model_name='node',
            name='types_arr',
            field=models.JSONField(default=platformpathapp.models.NodeTypes.get_default, validators=[platformpathapp.models.NodeTypes.validate_types]),
        ),
    ]
