# Generated by Django 6.0.5 on 2026-07-23 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformpathapp', '0010_remove_node_node_type_node_types_arr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='types_arr',
            new_name='types_dict',
        ),
    ]
