# Generated by Django 6.0.5 on 2026-08-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformpathapp', '0011_rename_types_arr_node_types_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='forward_vertical_direction',
            field=models.CharField(choices=[('NONE', 'None'), ('UP', 'Up'), ('DOWN', 'Down')], default='NONE', max_length=4),
        ),
    ]
