# Generated by Django 6.0.5 on 2026-08-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformpathapp', '0012_edge_forward_vertical_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='diagram_rotated_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
