# Generated by Django 6.0.5 on 2026-08-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformpathapp', '0013_station_diagram_rotated_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='is_accessible',
            new_name='is_accessible_infrastructure',
        ),
        migrations.AddField(
            model_name='station',
            name='accessible_station',
            field=models.BooleanField(default=False),
        ),
    ]
