# Generated by Django 6.0.5 on 2026-08-13 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformpathapp', '0014_rename_is_accessible_node_is_accessible_infrastructure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edge',
            old_name='instruction_backward',
            new_name='instruction',
        ),
        migrations.RenameField(
            model_name='edge',
            old_name='forward_vertical_direction',
            new_name='vertical_direction',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='instruction_forward',
        ),
    ]
