# Generated by Django 6.0.5 on 2026-09-20 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformpathapp', '0015_rename_instruction_backward_edge_instruction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='diagram_rotated_path',
        ),
    ]
