# Generated by Django 6.0.5 on 2026-09-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformpathapp', '0016_remove_station_diagram_rotated_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='road_map_high_res_grid_pic_paths',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='station',
            name='satellite_map_high_res_grid_pic_paths',
            field=models.JSONField(default=dict),
        ),
    ]
